### ISSUE TITLE
CMD Terminal Causes Browser Window to Close Unexpectedly During Navigation Commands

### ISSUE THREAD

**Issue by yzzzzye** [ishan0102/vimGPT#15]
Hello,

I'm new to programming and facing an issue with Vimium browser launched via CMD on Windows 10.
 After entering navigation commands, the browser crashes immediately.

I appreciate your assistance in resolving this issue. Please let me know if you need any more information. Could this issue be related to using Windows instead of Linux? Any help would be greatly appreciated.

Thank you!

Steps I did :
1. Launch Vimium browser through CMD on Windows 10.
2. Input any navigation command:  "google Rick Roll video"
3. Browser crashes instantly. and gives that code below

Error Code:
```
C:\vmgpt\vimGPT-main>python main.py
Initializing the Vimbot driver...
Navigating to Google...
Please enter your objective: google rick roll video
Capturing the screen...
Getting actions for the given objective...
Traceback (most recent call last):
  File "C:\vmgpt\vimGPT-main\main.py", line 29, in <module>
    main()
  File "C:\vmgpt\vimGPT-main\main.py", line 21, in main
    action = vision.get_actions(screenshot, objective)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vmgpt\vimGPT-main\vision.py", line 27, in get_actions
    response = openai.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_utils\_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\resources\chat\completions.py", line 564, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 834, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 854, in _request
    request = self._build_request(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 435, in _build_request
    headers = self._build_headers(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 393, in _build_headers
    headers = httpx.Headers(headers_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 70, in __init__
    self._list = [
                 ^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 74, in <listcomp>
    normalize_header_value(v, encoding),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iura9\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 210-212: ordinal not in range(128)
```

**Comment by lansmurf** [comment]
You are passing something up that cant be converted properly, are you sure that your openai api key is correct?

**Comment by ishan0102** [comment]
sorry for late response, most likely this is due to using CMD, should work with WSL or some other unix command line
